// Kutipan kategori "KataBiasa"
const kataBiasa = [
    "Believe in yourself and all that you are.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Your only limit is your mind.",
    "Don’t wait for opportunity, create it.",
    "The future depends on what you do today.",
    "You are capable of amazing things.",
    "Dare to be different.",
    "The best time for new beginnings is now.",
    "Push yourself, because no one else is going to do it for you.",
    "Believe you can and you're halfway there.",
    "Strength grows in the moments when you think you can’t go on but you keep going.",
    "Do something today that your future self will thank you for.",
    "The only person you should try to be better than is the person you were yesterday.",
    "It’s never too late to be what you might have been.",
    "Success doesn’t come from what you do occasionally, but what you do consistently.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Be the change that you wish to see in the world.",
    "Success is not in what you have, but who you are.",
    "You don’t have to be perfect to be amazing.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don’t stop when you’re tired, stop when you’re done.",
    "Doubt kills more dreams than failure ever will.",
    "The key to success is to focus on goals, not obstacles.",
    "Every day is a new beginning. Take a deep breath and start again.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "Small steps in the right direction can turn out to be the biggest step of your life.",
    "You don’t need to have it all figured out to move forward.",
    "Don’t limit your challenges; challenge your limits.",
    "Great things never come from comfort zones.",
    "You are stronger than you think.",
    "Dream it, wish it, do it.",
    "You can if you think you can.",
    "The road to success is always under construction.",
    "Fall seven times, stand up eight.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "It always seems impossible until it’s done.",
    "Your life does not get better by chance; it gets better by change.",
    "Take risks: If you win, you will be happy; if you lose, you will be wise.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don't be afraid to start over. It’s a chance to build something better.",
    "The best view comes after the hardest climb.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Discipline is the bridge between goals and accomplishment.",
    "Your journey is just as important as your destination.",
    "Life is tough, but so are you.",
    "Don’t let yesterday take up too much of today.",
    "You only fail when you stop trying.",
    "The best way to predict the future is to create it.",
    "Success is not for the lazy.",
    "Believe in your infinite potential.",
    "Act as if what you do makes a difference. It does.",
    "The harder you fall, the higher you bounce.",
    "Failure is not the opposite of success; it’s part of success.",
    "Do what you have to do until you can do what you want to do.",
    "If opportunity doesn’t knock, build a door.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Don't wait for the right moment. Make the moment right.",
    "Success is achieved by ordinary people with extraordinary determination.",
    "You miss 100% of the shots you don’t take.",
    "Hustle beats talent when talent doesn’t hustle.",
    "Your potential is endless.",
    "Focus on where you want to go, not on what you fear.",
    "Believe in yourself even when no one else does.",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
    "A winner is a dreamer who never gives up.",
    "Progress is progress, no matter how small.",
    "Stay positive, work hard, make it happen.",
    "Do something today that scares you.",
    "Don’t be pushed by your problems, be led by your dreams.",
    "Success isn’t always about greatness. It’s about consistency.",
    "Your dreams don’t work unless you do.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Rise above the storm and you will find the sunshine.",
    "Stay focused, stay positive, stay strong.",
    "You’ve got what it takes, but it will take everything you’ve got.",
    "Your best teacher is your last mistake.",
    "Don't compare your beginning to someone else's middle.",
    "Work for it more than you hope for it.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "Don’t wish for it; work for it.",
    "Focus on the good, and the good gets better.",
    "Success is a journey, not a destination.",
    "You don’t find willpower, you create it.",
    "The struggle you’re in today is developing the strength you need for tomorrow.",
    "You are the CEO of your own life.",
    "Success doesn’t come to you, you go to it.",
    "The best investment you can make is in yourself.",
    "Do what others won’t so you can live how others can’t.",
    "Self-confidence is the best outfit.",
    "Your attitude determines your direction.",
    "Stay patient and trust your journey.",
    "Success comes from having dreams bigger than your fears.",
    "You are what you do, not what you say you’ll do.",
    "Don’t fear failure, fear being in the same place next year as you are today.",
    "Dream big, start small, but most of all, start.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Be the hero of your own story."
];

// Kutipan kategori "KataBio"
const kataBio = [
    "Curious? My bio has all the answers!",
    "You won't believe what's in my bio!",
    "Check my bio for a little surprise!",
    "Want to know me better? My bio holds the key!",
    "Unlock the mystery in my bio!",
    "There's something special waiting in my bio!",
    "My bio is like a treasure map—follow it!",
    "Dive into my bio for a fun fact!",
    "If you’re intrigued, my bio has the scoop!",
    "You might find something you like in my bio!",
    "For the full story, head to my bio!",
    "There's more to me than meets the eye—check my bio!",
    "Spoiler alert: my bio is worth a peek!",
    "Want to know my secret? It’s in my bio!",
    "You won’t regret checking my bio!",
    "My bio is calling your name!",
    "Ever wondered about me? My bio tells all!",
    "Let my bio pique your curiosity!",
    "Trust me, my bio has a hidden gem!",
    "My bio is like a movie trailer—don’t miss it!",
    "Unlock the adventure in my bio!",
    "A little birdie told me to check my bio!",
    "There’s magic in my bio waiting for you!",
    "Get ready for a surprise in my bio!",
    "Feeling curious? My bio won’t disappoint!",
    "Peek into my bio for a sweet surprise!",
    "My bio is a must-read!",
    "My bio has the scoop—don’t miss it!",
    "There’s a twist in my bio just for you!",
    "Want a glimpse of my world? Check my bio!",
    "My bio has the answers to your questions!",
    "Catch a sneak peek into my life in my bio!",
    "Looking for fun? My bio has it!",
    "Don’t skip my bio—there’s something cool there!",
    "My bio is a hidden treasure—find it!",
    "A little curiosity never hurt—check my bio!",
    "Discover something new about me in my bio!",
    "My bio holds the secrets to my heart!",
    "A tiny adventure awaits you in my bio!",
    "You’ll want to see what’s in my bio!",
    "My bio is where the fun begins!",
    "Got a minute? My bio is worth your time!",
    "For the inside scoop, head to my bio!",
    "Want to flirt? Start by checking my bio!",
    "Every great story starts with a bio—check it out!",
    "My bio is where the magic happens!",
    "You might just fall for what’s in my bio!",
    "A little hint: my bio is intriguing!",
    "Curiosity leads to fun—check my bio!",
    "My bio has a little something for everyone!",
    "Step into my world through my bio!",
    "Don’t be shy; my bio is just a click away!",
    "There’s more than meets the eye in my bio!",
    "A treasure trove of fun awaits in my bio!",
    "Want to spark a connection? My bio is the place!",
    "Curious minds need to check my bio!",
    "My bio is a little window into my soul!",
    "You’ll find the best parts of me in my bio!",
    "For a good laugh, check my bio!",
    "My bio is the perfect conversation starter!",
    "Want to know my vibe? My bio tells all!",
    "Take a moment; my bio is worth it!",
    "Check my bio for a delightful surprise!",
    "You never know what you’ll find in my bio!",
    "Want to keep it fun? My bio is the key!",
    "A little exploration never hurt—check my bio!",
    "The best adventures start in my bio!",
    "Discover my quirks in my bio!",
    "My bio has the good stuff!",
    "For a little flirtation, look at my bio!",
    "Unlock my personality in my bio!",
    "My bio is your invitation to know me better!",
    "Check out my bio for some laughs!",
    "Every line in my bio is a little adventure!",
    "Curiosity is key—don’t forget my bio!",
    "There’s a fun twist in my bio just for you!",
    "If you’re intrigued, my bio is calling!",
    "Want to connect? My bio is the first step!",
    "My bio has a sprinkle of charm—don’t miss it!",
    "A little peek into my life? It’s all in my bio!",
    "My bio is your backstage pass to my world!",
    "Check my bio for some exciting insights!",
    "Let my bio inspire your next message!",
    "Every great story has a bio—read mine!",
    "Want to know what makes me tick? My bio has it!",
    "Take a chance—my bio might surprise you!",
    "Find the fun in my bio!",
    "You’ll find a delightful secret in my bio!",
    "My bio is the perfect icebreaker!",
    "Curiosity is a great trait—check my bio!",
    "My bio is where the fun begins!",
    "Explore my personality in my bio!",
    "Want a taste of my world? My bio is the way!",
    "Discover what makes me unique in my bio!",
    "Don’t overlook my bio—it’s got some charm!",
    "A little hint of mystery awaits in my bio!",
    "You might find your next favorite thing in my bio!",
    "For a dose of personality, check my bio!",
    "My bio is your roadmap to understanding me!",
    "Let’s make this interesting—start with my bio!"
];

// Kutipan kategori "KataLink"
const kataLink = [
    "𝐑𝐞𝐚𝐝𝐲 𝐭𝐨 𝐣𝐨𝐢𝐧 𝐭𝐡𝐞 𝐟𝐮𝐧? 𝐂𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞 𝐟𝐨𝐫 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦!	💦❣️👉"	,
    "𝐂𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞, 𝐫𝐢𝐠𝐡𝐭 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐃𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐚 𝐬𝐞𝐜𝐨𝐧𝐝, 𝐣𝐨𝐢𝐧 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦!	💦❣️👉"	,
    "𝐈𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐧𝐨𝐰! 𝐅𝐨𝐥𝐥𝐨𝐰 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐜𝐨𝐧𝐧𝐞𝐜𝐭 𝐥𝐢𝐯𝐞! 𝐖𝐚𝐭𝐜𝐡 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐓𝐡𝐞 𝐬𝐡𝐨𝐰 𝐢𝐬 𝐚𝐛𝐨𝐮𝐭 𝐭𝐨 𝐛𝐞𝐠𝐢𝐧, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐦𝐞 𝐥𝐢𝐯𝐞!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐬𝐞𝐞 𝐰𝐡𝐚𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠!	💦❣️👉"	,
    "𝐄𝐱𝐜𝐥𝐮𝐬𝐢𝐯𝐞 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦 𝐣𝐮𝐬𝐭 𝐟𝐨𝐫 𝐲𝐨𝐮, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐞𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 𝐬𝐨𝐦𝐞𝐭𝐡𝐢𝐧𝐠 𝐮𝐧𝐢𝐪𝐮𝐞!	💦❣️👉"	,
    "𝐋𝐢𝐯𝐞 𝐧𝐨𝐰! 𝐃𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐢𝐭, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐂𝐮𝐫𝐢𝐨𝐮𝐬? 𝐂𝐨𝐦𝐞 𝐜𝐡𝐞𝐜𝐤 𝐨𝐮𝐭 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐠𝐨 𝐥𝐢𝐯𝐞! 𝐅𝐨𝐥𝐥𝐨𝐰 𝐦𝐞 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐂𝐨𝐦𝐞 𝐬𝐞𝐞 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐣𝐨𝐢𝐧 𝐭𝐡𝐞 𝐟𝐮𝐧!	💦❣️👉"	,
    "𝐈𝐭’𝐬 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐧𝐨𝐰, 𝐣𝐨𝐢𝐧 𝐦𝐞!	💦❣️👉"	,
    "𝐖𝐚𝐧𝐭 𝐦𝐨𝐫𝐞? 𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐧𝐨𝐰, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞 𝐭𝐨 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐒𝐞𝐞 𝐢𝐭 𝐚𝐥𝐥 𝐮𝐧𝐟𝐨𝐥𝐝 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐂𝐚𝐭𝐜𝐡 𝐭𝐡𝐞 𝐚𝐜𝐭𝐢𝐨𝐧 𝐥𝐢𝐯𝐞, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐦𝐞 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐡𝐚𝐯𝐞 𝐟𝐮𝐧 𝐥𝐢𝐯𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐭𝐨 𝐣𝐨𝐢𝐧!	💦❣️👉"	,
    "𝐄𝐱𝐜𝐥𝐮𝐬𝐢𝐯𝐞 𝐦𝐨𝐦𝐞𝐧𝐭𝐬 𝐥𝐢𝐯𝐞, 𝐨𝐧𝐥𝐲 𝐟𝐨𝐫 𝐲𝐨𝐮!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐫𝐢𝐠𝐡𝐭 𝐧𝐨𝐰, 𝐜𝐨𝐦𝐞 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐃𝐨𝐧’𝐭 𝐰𝐚𝐢𝐭, 𝐣𝐨𝐢𝐧 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐆𝐞𝐭 𝐢𝐧 𝐨𝐧 𝐭𝐡𝐞 𝐚𝐜𝐭𝐢𝐨𝐧, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐦𝐞 𝐥𝐢𝐯𝐞!	💦❣️👉"	,
    "𝐘𝐨𝐮 𝐝𝐨𝐧’𝐭 𝐰𝐚𝐧𝐭 𝐭𝐨 𝐦𝐢𝐬𝐬 𝐭𝐡𝐢𝐬 𝐥𝐢𝐯𝐞!	💦❣️👉"	,
    "𝐋𝐢𝐯𝐞 𝐧𝐨𝐰! 𝐂𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞 𝐭𝐨 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐈’𝐦 𝐰𝐚𝐢𝐭𝐢𝐧𝐠 𝐟𝐨𝐫 𝐲𝐨𝐮 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐄𝐱𝐜𝐢𝐭𝐢𝐧𝐠 𝐭𝐡𝐢𝐧𝐠𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐥𝐢𝐯𝐞, 𝐝𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐢𝐭!	💦❣️👉"	,
    "𝐁𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐭𝐡𝐞 𝐥𝐢𝐯𝐞 𝐟𝐮𝐧, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐦𝐞!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐡𝐚𝐧𝐠 𝐨𝐮𝐭 𝐥𝐢𝐯𝐞! 𝐂𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞, 𝐢𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐂𝐨𝐦𝐞 𝐣𝐨𝐢𝐧 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦 𝐚𝐧𝐝 𝐜𝐡𝐚𝐭!	💦❣️👉"	,
    "𝐒𝐞𝐞 𝐢𝐭 𝐥𝐢𝐯𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞 𝐭𝐨 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐰𝐚𝐢𝐭𝐢𝐧𝐠, 𝐣𝐨𝐢𝐧 𝐦𝐞!	💦❣️👉"	,
    "𝐋𝐢𝐯𝐞 𝐦𝐨𝐦𝐞𝐧𝐭𝐬 𝐣𝐮𝐬𝐭 𝐟𝐨𝐫 𝐲𝐨𝐮, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐂𝐨𝐦𝐞 𝐞𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 𝐢𝐭 𝐥𝐢𝐯𝐞 𝐰𝐢𝐭𝐡 𝐦𝐞!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐠𝐨 𝐥𝐢𝐯𝐞 𝐭𝐨𝐠𝐞𝐭𝐡𝐞𝐫! 𝐂𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐓𝐡𝐞 𝐟𝐮𝐧 𝐢𝐬 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐦𝐞 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐘𝐨𝐮’𝐫𝐞 𝐢𝐧𝐯𝐢𝐭𝐞𝐝 𝐭𝐨 𝐰𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞!	💦❣️👉"	,
    "𝐃𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐨𝐮𝐭, 𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐫𝐢𝐠𝐡𝐭 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐋𝐢𝐯𝐞 𝐚𝐧𝐝 𝐢𝐧𝐭𝐞𝐫𝐚𝐜𝐭𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐦𝐞 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐒𝐞𝐞 𝐢𝐭 𝐚𝐥𝐥 𝐥𝐢𝐯𝐞, 𝐣𝐮𝐬𝐭 𝐜𝐥𝐢𝐜𝐤!	💦❣️👉"	,
    "𝐈𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐥𝐢𝐯𝐞! 𝐅𝐨𝐥𝐥𝐨𝐰 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐄𝐱𝐜𝐥𝐮𝐬𝐢𝐯𝐞 𝐜𝐨𝐧𝐭𝐞𝐧𝐭 𝐥𝐢𝐯𝐞, 𝐰𝐚𝐭𝐜𝐡 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐂𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐞𝐧𝐣𝐨𝐲 𝐭𝐡𝐞 𝐬𝐡𝐨𝐰!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐡𝐚𝐯𝐞 𝐬𝐨𝐦𝐞 𝐥𝐢𝐯𝐞 𝐟𝐮𝐧, 𝐣𝐨𝐢𝐧 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐥𝐞𝐭’𝐬 𝐜𝐨𝐧𝐧𝐞𝐜𝐭!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐟𝐨𝐫 𝐬𝐨𝐦𝐞𝐭𝐡𝐢𝐧𝐠 𝐬𝐩𝐞𝐜𝐢𝐚𝐥!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐫𝐞𝐚𝐝𝐲, 𝐚𝐫𝐞 𝐲𝐨𝐮? 𝐂𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐂𝐨𝐦𝐞 𝐰𝐚𝐭𝐜𝐡 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐛𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐭𝐡𝐞 𝐦𝐨𝐦𝐞𝐧𝐭!	💦❣️👉"	,
    "𝐃𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐨𝐮𝐭, 𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐫𝐢𝐠𝐡𝐭 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐈𝐭’𝐬 𝐚𝐥𝐥 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐄𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 𝐢𝐭 𝐥𝐢𝐯𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐭𝐨 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐣𝐮𝐬𝐭 𝐟𝐨𝐫 𝐲𝐨𝐮, 𝐜𝐨𝐦𝐞 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐒𝐞𝐞 𝐞𝐯𝐞𝐫𝐲𝐭𝐡𝐢𝐧𝐠 𝐥𝐢𝐯𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐂𝐨𝐦𝐞 𝐬𝐞𝐞 𝐰𝐡𝐚𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐥𝐢𝐯𝐞 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐭𝐡𝐞 𝐥𝐢𝐯𝐞 𝐟𝐮𝐧, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐛𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐭𝐡𝐞 𝐚𝐜𝐭𝐢𝐨𝐧!	💦❣️👉"	,
    "𝐓𝐡𝐞 𝐞𝐱𝐜𝐢𝐭𝐞𝐦𝐞𝐧𝐭 𝐢𝐬 𝐥𝐢𝐯𝐞, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐦𝐞 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐋𝐢𝐯𝐞 𝐧𝐨𝐰! 𝐃𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐭𝐡𝐞 𝐟𝐮𝐧!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐜𝐡𝐚𝐭 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐦𝐞 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐢𝐭’𝐬 𝐚𝐥𝐥 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐟𝐨𝐫 𝐚 𝐬𝐩𝐞𝐜𝐢𝐚𝐥 𝐦𝐨𝐦𝐞𝐧𝐭!	💦❣️👉"	,
    "𝐁𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐬𝐨𝐦𝐞𝐭𝐡𝐢𝐧𝐠 𝐥𝐢𝐯𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐫𝐞𝐚𝐝𝐲 𝐟𝐨𝐫 𝐲𝐨𝐮, 𝐣𝐨𝐢𝐧 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐃𝐨𝐧’𝐭 𝐰𝐚𝐢𝐭, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦!	💦❣️👉"	,
    "𝐒𝐞𝐞 𝐦𝐞 𝐥𝐢𝐯𝐞, 𝐣𝐮𝐬𝐭 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐋𝐢𝐯𝐞 𝐧𝐨𝐰, 𝐝𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐭𝐡𝐞 𝐚𝐜𝐭𝐢𝐨𝐧!	💦❣️👉"	,
    "𝐂𝐨𝐦𝐞 𝐰𝐚𝐭𝐜𝐡 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐥𝐞𝐭’𝐬 𝐡𝐚𝐯𝐞 𝐟𝐮𝐧!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐛𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐢𝐭 𝐚𝐥𝐥!	💦❣️👉"	,
    "𝐂𝐚𝐭𝐜𝐡 𝐚𝐥𝐥 𝐭𝐡𝐞 𝐚𝐜𝐭𝐢𝐨𝐧 𝐥𝐢𝐯𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐢𝐭’𝐬 𝐚𝐥𝐥 𝐟𝐨𝐫 𝐲𝐨𝐮!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐈𝐭’𝐬 𝐥𝐢𝐯𝐞, 𝐢𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐠𝐨 𝐥𝐢𝐯𝐞 𝐭𝐨𝐠𝐞𝐭𝐡𝐞𝐫, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐁𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐭𝐡𝐞 𝐥𝐢𝐯𝐞 𝐞𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐦𝐲 𝐥𝐢𝐯𝐞 𝐜𝐚𝐦 𝐚𝐧𝐝 𝐥𝐞𝐭’𝐬 𝐜𝐨𝐧𝐧𝐞𝐜𝐭!	💦❣️👉"	,
    "𝐃𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐭𝐡𝐢𝐬 𝐥𝐢𝐯𝐞 𝐦𝐨𝐦𝐞𝐧𝐭, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐂𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞, 𝐢𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐫𝐢𝐠𝐡𝐭 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐣𝐮𝐬𝐭 𝐟𝐨𝐫 𝐲𝐨𝐮, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐦𝐞 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐋𝐞𝐭’𝐬 𝐜𝐡𝐚𝐭 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐦𝐞 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐈𝐭’𝐬 𝐚𝐥𝐥 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐥𝐢𝐯𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐭𝐨 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐄𝐱𝐜𝐥𝐮𝐬𝐢𝐯𝐞 𝐦𝐨𝐦𝐞𝐧𝐭𝐬 𝐥𝐢𝐯𝐞, 𝐝𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐢𝐭!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐛𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐭𝐡𝐞 𝐟𝐮𝐧!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐭𝐡𝐞 𝐥𝐢𝐯𝐞 𝐚𝐜𝐭𝐢𝐨𝐧, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐧𝐨𝐰, 𝐜𝐨𝐦𝐞 𝐰𝐚𝐭𝐜𝐡!	💦❣️👉"	,
    "𝐄𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 𝐢𝐭 𝐚𝐥𝐥 𝐥𝐢𝐯𝐞, 𝐟𝐨𝐥𝐥𝐨𝐰 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐟𝐨𝐫 𝐬𝐨𝐦𝐞𝐭𝐡𝐢𝐧𝐠 𝐬𝐩𝐞𝐜𝐢𝐚𝐥!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐰𝐚𝐢𝐭𝐢𝐧𝐠, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐒𝐞𝐞 𝐰𝐡𝐚𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐃𝐨𝐧’𝐭 𝐦𝐢𝐬𝐬 𝐭𝐡𝐢𝐬 𝐥𝐢𝐯𝐞 𝐞𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐈𝐭’𝐬 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐞𝐱𝐜𝐢𝐭𝐢𝐧𝐠, 𝐣𝐨𝐢𝐧 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐂𝐨𝐦𝐞 𝐛𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐭𝐡𝐞 𝐥𝐢𝐯𝐞 𝐟𝐮𝐧, 𝐜𝐥𝐢𝐜𝐤 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐥𝐞𝐭’𝐬 𝐜𝐡𝐚𝐭!	💦❣️👉"	,
    "𝐂𝐚𝐭𝐜𝐡 𝐚𝐥𝐥 𝐭𝐡𝐞 𝐞𝐱𝐜𝐢𝐭𝐞𝐦𝐞𝐧𝐭 𝐥𝐢𝐯𝐞, 𝐣𝐨𝐢𝐧 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐓𝐡𝐞 𝐥𝐢𝐯𝐞 𝐟𝐮𝐧 𝐢𝐬 𝐬𝐭𝐚𝐫𝐭𝐢𝐧𝐠 𝐧𝐨𝐰, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐲𝐨𝐮 𝐝𝐨𝐧’𝐭 𝐰𝐚𝐧𝐭 𝐭𝐨 𝐦𝐢𝐬𝐬 𝐢𝐭!	💦❣️👉"	,
    "𝐁𝐞 𝐩𝐚𝐫𝐭 𝐨𝐟 𝐭𝐡𝐞 𝐥𝐢𝐯𝐞 𝐞𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞, 𝐜𝐥𝐢𝐜𝐤 𝐡𝐞𝐫𝐞!	💦❣️👉"	,
    "𝐖𝐚𝐭𝐜𝐡 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐣𝐨𝐢𝐧 𝐭𝐡𝐞 𝐟𝐮𝐧!	💦❣️👉"	,
    "𝐈’𝐦 𝐥𝐢𝐯𝐞 𝐚𝐧𝐝 𝐢𝐭’𝐬 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠 𝐧𝐨𝐰!	💦❣️👉"	,
    "𝐉𝐨𝐢𝐧 𝐦𝐞 𝐥𝐢𝐯𝐞 𝐟𝐨𝐫 𝐚𝐧 𝐮𝐧𝐟𝐨𝐫𝐠𝐞𝐭𝐭𝐚𝐛𝐥𝐞 𝐦𝐨𝐦𝐞𝐧𝐭!	💦❣️👉"
    ]

// Elemen HTML
const quoteText = document.getElementById('quote');
const quoteCategory = document.getElementById('quote-category');
const generateQuoteBtn = document.getElementById('generate-quote');
const copyQuoteBtn = document.getElementById('copy-quote');

// Fungsi untuk mendapatkan kutipan acak
function getRandomQuote(quotesArray) {
    const randomIndex = Math.floor(Math.random() * quotesArray.length);
    return quotesArray[randomIndex];
}

// Fungsi untuk menghasilkan kutipan berdasarkan kategori yang dipilih
function generateQuote() {
    const selectedCategory = quoteCategory.value;

    if (selectedCategory === 'biasa') {
        quoteText.value = getRandomQuote(kataBiasa);
    } else if (selectedCategory === 'bio') {
        quoteText.value = getRandomQuote(kataBio);
    } else if (selectedCategory === 'link') {
        quoteText.value = getRandomQuote(kataLink); // gunakan value karena ini textarea
    }
}

// Fungsi untuk menyalin kutipan ke clipboard
function copyQuote() {
    quoteText.select();
    document.execCommand("copy");
    alert("Sriiiiitttt.....!!!");
}

// Event listener untuk tombol "Generate"
generateQuoteBtn.addEventListener('click', generateQuote);

// Event listener untuk tombol "Copy"
copyQuoteBtn.addEventListener('click', copyQuote);



